# Generated by Django 4.0.2 on 2023-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/user_logo_default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
