# Generated by Django 4.0.2 on 2023-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='visibility',
            field=models.CharField(default='for_all', max_length=10),
        ),
    ]
